### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by brendan-rius** [flesler/jwt-crack#1]
I tried beaking a very simple JWT with secret `a`and it was obviously very fast:

```
node index.js 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.GTIYrxbQ8xcdhJMhMSXk8Af1yVT8U3uPWivXp6qjjWA'
2017-01-19 15:26:04> Cracked secret in 2 attempts, took 0.0 minutes, secret is a
```

But now I want to crack another very very simple JWT with secret `ab` and it seems like it is working but doing nothing:

```
node index.js 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.4EPGTPOs4Y5su820_z1jjIypbzEleqD_hHIpSsxMx74'
^C2017-01-19 15:28:28> Failed to crack secret in 20398134 attempts, took 2.0 minutes
```

I had to CTRL+C after 2 minutes because it did not find that very simple key. How come?

**Comment by flesler** [comment]
I detected the problem. Node's crypto module result has slashes (/) where yours has underscores. 

I tested your JWT on jwt.io, both signatures (slashes and underscores) work with the same secret so it seems there's a normalization step I'm missing. I'll see if I can find any documentation on this.

Your call above will work if you change underscores for slashes. One simple option is to normalize the incoming signature when starting, will let you know if I can find anything

**Comment by flesler** [comment]
Fixed, published to NPM as version 1.1.1

**Comment by brendan-rius** [comment]
Thank you! :)
I developed mine in the meantime. Although it is not yet multithreaded, it it fast because coded in C : https://github.com/brendan-rius/c-jwt-cracker :)

**Comment by flesler** [comment]
You should compare both to see how much faster, you can run this one in a single thread with --cpus=1 though it won't be a fair comparison but good enough for now

**Comment by brendan-rius** [comment]
```
./jwtcrack eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE

Secret is "Sn1f"
Time taken 23 seconds 982 milliseconds
```

vs

```
node index.js --cpus=1 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE
2017-01-20 19:25:52> Cracked secret in 10272608 attempts, took 0.9 minutes, secret is Sn1f
```

**Comment by flesler** [comment]
Great, I run it on my end (only Node version)
```
$ node index.js eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE --cpus=1
2017-01-23 17:05:17> Cracked secret in 10272608 attempts, took 0.8 minutes, secret is Sn1f
```
```
$ node index.js eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE
2017-01-23 17:05:45> Cracked secret in 10272608 attempts, took 0.2 minutes, secret is Sn1f
```



The single core version was slightly faster on my computer (48 seconds). The multi-core took 25% of the time, as expected given my computer is a quad core. It took 12 seconds. This Node.js version seems to take approximately twice as long as yours.

**Comment by flesler** [comment]
Great, I ran it on my end (only Node version)
```
$ node -v
v6.9.4
```
```
$ node index.js  --cpus=1
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE
2017-01-23 17:05:17> Cracked secret in 10272608 attempts, took 0.8 minutes, secret is Sn1f
```
```
$ node index.js eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.cAOIAifu3fykvhkHpbuhbvtH807-Z2rI1FS3vX1XMjE
2017-01-23 17:05:45> Cracked secret in 10272608 attempts, took 0.2 minutes, secret is Sn1f
```

The single core version was slightly faster on my computer (48 seconds). The multi-core took 25% of that, as expected given my computer is a quad core. It took 12 seconds. This Node.js version seems to take approximately twice as long as yours.
